### PR TITLE
Random forest can now take user defined parameters.

### PR DESCRIPTION
**Pull request by arose13**
The current implementation of MERF only allows the user to set the number of trees in the random forest. This pull request allows the user to set any parameter they want but prevents them from changing important params like having the out of bag score on.

I hope you accept this it has been useful for me.

### CODE REVIEW

**Comment by arose13** [comment]
Hey, I am absolutely not clear what is wrong with the CI tests when I'm able to pass on tests on my local machine.

```
7 of 7 tests passed in 8.044s

OK
```

**Comment by resdntalien** [comment]
So sorry for the lateness of this. Will take a look at this and try to get it merged in!

**Comment by resdntalien** [comment]
Look like the CI failing is a Lint issue

Screen Shot 2019-03-27 at 8 42 53 PM

**Review by resdntalien — APPROVED** [review]
This is a good change. I'll approve and merge.

**Pull request merged**
